# Generated by Django 5.2 on 2025-04-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_payslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='deductions_health',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='deductions_tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='earnings_allowance',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='overtime',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='pag_ibig',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='total_pay',
        ),
    ]
