# Generated by Django 5.2 on 2025-05-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0004_remove_payslip_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
