# Generated by Django 5.2 on 2025-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0005_payslip_rate_payslip_total_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='earnings_allowance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
