# Generated by Django 5.2 on 2025-05-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0006_payslip_earnings_allowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
