# Generated by Django 5.2 on 2025-05-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0007_payslip_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='deductions_health',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
