# Generated by Django 5.2 on 2025-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0008_payslip_deductions_health_payslip_pag_ibig'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='deductions_tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
