# Generated by Django 5.2 on 2025-05-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0009_payslip_deductions_tax_payslip_sss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='deductions_health',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='pag_ibig',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='sss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
