# Generated by Django 5.2 on 2025-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0010_alter_payslip_deductions_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='earnings_allowance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
