# Generated by Django 5.2 on 2025-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0011_alter_payslip_earnings_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='monthlyRate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
