# Generated by Django 5.2 on 2025-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0012_payslip_monthlyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
