# Generated by Django 5.2 on 2025-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0013_payslip_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date_range',
            field=models.CharField(max_length=250),
        ),
    ]
