# Generated by Django 5.2 on 2025-05-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0014_alter_payslip_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='overtime',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
