# Generated by Django 5.2 on 2025-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0015_alter_payslip_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overtime_pay',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
