# Generated by Django 5.2 on 2025-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0016_alter_employee_overtime_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
